package mirora.entity;
// Generated Nov 4, 2020 4:35:21 PM by Hibernate Tools 4.3.1



/**
 * Banner generated by hbm2java
 */
public class Banner  implements java.io.Serializable {


     private int bannerId;
     private String bannerName;
     private String imagelink;
     private String bannerLink;
     private Integer bannerPriority;
     private Boolean bannerStatus;

    public Banner() {
    }

	
    public Banner(int bannerId) {
        this.bannerId = bannerId;
    }
    public Banner(int bannerId, String bannerName, String imagelink, String bannerLink, Integer bannerPriority, Boolean bannerStatus) {
       this.bannerId = bannerId;
       this.bannerName = bannerName;
       this.imagelink = imagelink;
       this.bannerLink = bannerLink;
       this.bannerPriority = bannerPriority;
       this.bannerStatus = bannerStatus;
    }
   
    public int getBannerId() {
        return this.bannerId;
    }
    
    public void setBannerId(int bannerId) {
        this.bannerId = bannerId;
    }
    public String getBannerName() {
        return this.bannerName;
    }
    
    public void setBannerName(String bannerName) {
        this.bannerName = bannerName;
    }
    public String getImagelink() {
        return this.imagelink;
    }
    
    public void setImagelink(String imagelink) {
        this.imagelink = imagelink;
    }
    public String getBannerLink() {
        return this.bannerLink;
    }
    
    public void setBannerLink(String bannerLink) {
        this.bannerLink = bannerLink;
    }
    public Integer getBannerPriority() {
        return this.bannerPriority;
    }
    
    public void setBannerPriority(Integer bannerPriority) {
        this.bannerPriority = bannerPriority;
    }
    public Boolean getBannerStatus() {
        return this.bannerStatus;
    }
    
    public void setBannerStatus(Boolean bannerStatus) {
        this.bannerStatus = bannerStatus;
    }




}


