package mirora.entity;
// Generated Nov 4, 2020 4:35:21 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
public class Categories  implements java.io.Serializable {


     private int catalogId;
     private String catName;
     private Integer catPriority;
     private String catDescription;
     private Integer parentId;
     private Boolean catStatus;
     private Set catProducts = new HashSet(0);

    public Categories() {
    }

	
    public Categories(int catalogId) {
        this.catalogId = catalogId;
    }
    public Categories(int catalogId, String catName, Integer catPriority, String catDescription, Integer parentId, Boolean catStatus, Set catProducts) {
       this.catalogId = catalogId;
       this.catName = catName;
       this.catPriority = catPriority;
       this.catDescription = catDescription;
       this.parentId = parentId;
       this.catStatus = catStatus;
       this.catProducts = catProducts;
    }
   
    public int getCatalogId() {
        return this.catalogId;
    }
    
    public void setCatalogId(int catalogId) {
        this.catalogId = catalogId;
    }
    public String getCatName() {
        return this.catName;
    }
    
    public void setCatName(String catName) {
        this.catName = catName;
    }
    public Integer getCatPriority() {
        return this.catPriority;
    }
    
    public void setCatPriority(Integer catPriority) {
        this.catPriority = catPriority;
    }
    public String getCatDescription() {
        return this.catDescription;
    }
    
    public void setCatDescription(String catDescription) {
        this.catDescription = catDescription;
    }
    public Integer getParentId() {
        return this.parentId;
    }
    
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
    public Boolean getCatStatus() {
        return this.catStatus;
    }
    
    public void setCatStatus(Boolean catStatus) {
        this.catStatus = catStatus;
    }
    public Set getCatProducts() {
        return this.catProducts;
    }
    
    public void setCatProducts(Set catProducts) {
        this.catProducts = catProducts;
    }




}


