package mirora.entity;
// Generated Nov 4, 2020 4:35:21 PM by Hibernate Tools 4.3.1



/**
 * CatProduct generated by hbm2java
 */
public class CatProduct  implements java.io.Serializable {


     private int catProId;
     private Categories categories;
     private Product product;

    public CatProduct() {
    }

	
    public CatProduct(int catProId) {
        this.catProId = catProId;
    }
    public CatProduct(int catProId, Categories categories, Product product) {
       this.catProId = catProId;
       this.categories = categories;
       this.product = product;
    }
   
    public int getCatProId() {
        return this.catProId;
    }
    
    public void setCatProId(int catProId) {
        this.catProId = catProId;
    }
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }




}


