package mirora.entity;
// Generated Nov 4, 2020 4:35:21 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Colors generated by hbm2java
 */
public class Colors  implements java.io.Serializable {


     private int colorId;
     private String colorName;
     private Boolean colorStatus;
     private Set productDetails = new HashSet(0);

    public Colors() {
    }

	
    public Colors(int colorId) {
        this.colorId = colorId;
    }
    public Colors(int colorId, String colorName, Boolean colorStatus, Set productDetails) {
       this.colorId = colorId;
       this.colorName = colorName;
       this.colorStatus = colorStatus;
       this.productDetails = productDetails;
    }
   
    public int getColorId() {
        return this.colorId;
    }
    
    public void setColorId(int colorId) {
        this.colorId = colorId;
    }
    public String getColorName() {
        return this.colorName;
    }
    
    public void setColorName(String colorName) {
        this.colorName = colorName;
    }
    public Boolean getColorStatus() {
        return this.colorStatus;
    }
    
    public void setColorStatus(Boolean colorStatus) {
        this.colorStatus = colorStatus;
    }
    public Set getProductDetails() {
        return this.productDetails;
    }
    
    public void setProductDetails(Set productDetails) {
        this.productDetails = productDetails;
    }




}


