package mirora.entity;
// Generated Nov 4, 2020 4:35:21 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * News generated by hbm2java
 */
public class News  implements java.io.Serializable {


     private int newsId;
     private NewType newType;
     private Date createDate;
     private Serializable tittle;
     private Serializable newsDescription;
     private Boolean newsStatus;

    public News() {
    }

	
    public News(int newsId) {
        this.newsId = newsId;
    }
    public News(int newsId, NewType newType, Date createDate, Serializable tittle, Serializable newsDescription, Boolean newsStatus) {
       this.newsId = newsId;
       this.newType = newType;
       this.createDate = createDate;
       this.tittle = tittle;
       this.newsDescription = newsDescription;
       this.newsStatus = newsStatus;
    }
   
    public int getNewsId() {
        return this.newsId;
    }
    
    public void setNewsId(int newsId) {
        this.newsId = newsId;
    }
    public NewType getNewType() {
        return this.newType;
    }
    
    public void setNewType(NewType newType) {
        this.newType = newType;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Serializable getTittle() {
        return this.tittle;
    }
    
    public void setTittle(Serializable tittle) {
        this.tittle = tittle;
    }
    public Serializable getNewsDescription() {
        return this.newsDescription;
    }
    
    public void setNewsDescription(Serializable newsDescription) {
        this.newsDescription = newsDescription;
    }
    public Boolean getNewsStatus() {
        return this.newsStatus;
    }
    
    public void setNewsStatus(Boolean newsStatus) {
        this.newsStatus = newsStatus;
    }




}


