package mirora.entity;
// Generated Nov 4, 2020 4:35:21 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private int orderId;
     private Users users;
     @DateTimeFormat(pattern = "yyyy-MM-dd")
     private Date createdDate;
     private float totalAmount;
     private Boolean orderStatus;
     private Set orderDetails = new HashSet(0);

    public Orders() {
    }

	
    public Orders(int orderId) {
        this.orderId = orderId;
    }
    public Orders(int orderId, Users users, Date createdDate, float totalAmount, Boolean orderStatus, Set orderDetails) {
       this.orderId = orderId;
       this.users = users;
       this.createdDate = createdDate;
       this.totalAmount = totalAmount;
       this.orderStatus = orderStatus;
       this.orderDetails = orderDetails;
    }
   
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public float getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(float totalAmount) {
        this.totalAmount = totalAmount;
    }
    public Boolean getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(Boolean orderStatus) {
        this.orderStatus = orderStatus;
    }
    public Set getOrderDetails() {
        return this.orderDetails;
    }
    
    public void setOrderDetails(Set orderDetails) {
        this.orderDetails = orderDetails;
    }




}


