package mirora.entity;
// Generated Nov 4, 2020 4:35:21 PM by Hibernate Tools 4.3.1



/**
 * OrderDetail generated by hbm2java
 */
public class OrderDetail  implements java.io.Serializable {


     private int orderDetailId;
     private Orders orders;
     private ProductDetail productDetail;
     private Integer quantity;
     private Double amount;
     private Boolean orderStatus;

    public OrderDetail() {
    }

	
    public OrderDetail(int orderDetailId) {
        this.orderDetailId = orderDetailId;
    }
    public OrderDetail(int orderDetailId, Orders orders, ProductDetail productDetail, Integer quantity, Double amount, Boolean orderStatus) {
       this.orderDetailId = orderDetailId;
       this.orders = orders;
       this.productDetail = productDetail;
       this.quantity = quantity;
       this.amount = amount;
       this.orderStatus = orderStatus;
    }
   
    public int getOrderDetailId() {
        return this.orderDetailId;
    }
    
    public void setOrderDetailId(int orderDetailId) {
        this.orderDetailId = orderDetailId;
    }
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }
    public ProductDetail getProductDetail() {
        return this.productDetail;
    }
    
    public void setProductDetail(ProductDetail productDetail) {
        this.productDetail = productDetail;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public Boolean getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(Boolean orderStatus) {
        this.orderStatus = orderStatus;
    }




}


