package mirora.entity;
// Generated Nov 4, 2020 4:35:21 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

    private String productId;
    private String productName;
    private String title;
    private String productDescription;
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date createdDate;
    private String imageMain;
    private Double discount;
    private Integer productView;
    private Double price;
    private Boolean productStatus;
    private Set starses = new HashSet(0);
    private Set comments = new HashSet(0);
    private Set imageses = new HashSet(0);
    private Set favorites = new HashSet(0);
    private Set productDetails = new HashSet(0);
    private Set catProducts = new HashSet(0);
    private List<String> listCate;
    private List<String> colors;
    private List<String> quantity;

    public Product() {
    }

    public Product(String productId) {
        this.productId = productId;
    }
    
    public Product(String productId, String productName, String title, String productDescription, Date createdDate, String imageMain, Double discount, Integer productView, Double price, Boolean productStatus, Set starses, Set comments, Set imageses, Set favorites, Set productDetails, Set catProducts) {
        this.productId = productId;
        this.productName = productName;
        this.title = title;
        this.productDescription = productDescription;
        this.createdDate = createdDate;
        this.imageMain = imageMain;
        this.discount = discount;
        this.productView = productView;
        this.price = price;
        this.productStatus = productStatus;
        this.starses = starses;
        this.comments = comments;
        this.imageses = imageses;
        this.favorites = favorites;
        this.productDetails = productDetails;
        this.catProducts = catProducts;
    }

    public String getProductId() {
        return this.productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public String getProductName() {
        return this.productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getProductDescription() {
        return this.productDescription;
    }

    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription;
    }

    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public String getImageMain() {
        return this.imageMain;
    }

    public void setImageMain(String imageMain) {
        this.imageMain = imageMain;
    }

    public Double getDiscount() {
        return this.discount;
    }

    public void setDiscount(Double discount) {
        this.discount = discount;
    }

    public Integer getProductView() {
        return this.productView;
    }

    public void setProductView(Integer productView) {
        this.productView = productView;
    }

    public Double getPrice() {
        return this.price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public Boolean getProductStatus() {
        return this.productStatus;
    }

    public void setProductStatus(Boolean productStatus) {
        this.productStatus = productStatus;
    }

    public Set getStarses() {
        return this.starses;
    }

    public void setStarses(Set starses) {
        this.starses = starses;
    }

    public Set getComments() {
        return this.comments;
    }

    public void setComments(Set comments) {
        this.comments = comments;
    }

    public Set getImageses() {
        return this.imageses;
    }

    public void setImageses(Set imageses) {
        this.imageses = imageses;
    }

    public Set getFavorites() {
        return this.favorites;
    }

    public void setFavorites(Set favorites) {
        this.favorites = favorites;
    }

    public Set getProductDetails() {
        return this.productDetails;
    }

    public void setProductDetails(Set productDetails) {
        this.productDetails = productDetails;
    }

    public Set getCatProducts() {
        return this.catProducts;
    }

    public void setCatProducts(Set catProducts) {
        this.catProducts = catProducts;
    }

    public List<String> getListCate() {
        return listCate;
    }

    public void setListCate(List<String> listCate) {
        this.listCate = listCate;
    }

    public List<String> getColors() {
        return colors;
    }

    public void setColors(List<String> colors) {
        this.colors = colors;
    }

    public List<String> getQuantity() {
        return quantity;
    }

    public void setQuantity(List<String> quantity) {
        this.quantity = quantity;
    }
    
    public ProductDetail getOneProdetail(String color) {
        int colorId = Integer.parseInt(color);
        ProductDetail proD = null;
        for (Object obj : getProductDetails()) {
            ProductDetail proDetail = (ProductDetail) obj;
            if (proDetail.getColors().getColorId() == colorId) {
                proD = proDetail;
            }
        }
        return proD;
    }
}
