package mirora.entity;
// Generated Nov 4, 2020 4:35:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ProductDetail generated by hbm2java
 */
public class ProductDetail  implements java.io.Serializable {


     private int productDetailId;
     private Colors colors;
     private Product product;
     private Integer quantity;
     private Boolean productDtStatus;
     private Set orderDetails = new HashSet(0);

    public ProductDetail() {
    }

	
    public ProductDetail(int productDetailId) {
        this.productDetailId = productDetailId;
    }
    public ProductDetail(int productDetailId, Colors colors, Product product, Integer quantity, Boolean productDtStatus, Set orderDetails) {
       this.productDetailId = productDetailId;
       this.colors = colors;
       this.product = product;
       this.quantity = quantity;
       this.productDtStatus = productDtStatus;
       this.orderDetails = orderDetails;
    }
   
    public int getProductDetailId() {
        return this.productDetailId;
    }
    
    public void setProductDetailId(int productDetailId) {
        this.productDetailId = productDetailId;
    }
    public Colors getColors() {
        return this.colors;
    }
    
    public void setColors(Colors colors) {
        this.colors = colors;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public Boolean getProductDtStatus() {
        return this.productDtStatus;
    }
    
    public void setProductDtStatus(Boolean productDtStatus) {
        this.productDtStatus = productDtStatus;
    }
    public Set getOrderDetails() {
        return this.orderDetails;
    }
    
    public void setOrderDetails(Set orderDetails) {
        this.orderDetails = orderDetails;
    }




}


