package mirora.entity;
// Generated Nov 4, 2020 4:35:21 PM by Hibernate Tools 4.3.1



/**
 * Stars generated by hbm2java
 */
public class Stars  implements java.io.Serializable {


     private int starId;
     private Product product;
     private Users users;
     private Integer mark;

    public Stars() {
    }

	
    public Stars(int starId) {
        this.starId = starId;
    }
    public Stars(int starId, Product product, Users users, Integer mark) {
       this.starId = starId;
       this.product = product;
       this.users = users;
       this.mark = mark;
    }
   
    public int getStarId() {
        return this.starId;
    }
    
    public void setStarId(int starId) {
        this.starId = starId;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Integer getMark() {
        return this.mark;
    }
    
    public void setMark(Integer mark) {
        this.mark = mark;
    }




}


