package mirora.entity;
// Generated Nov 4, 2020 4:35:21 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * SystemWatch generated by hbm2java
 */
public class SystemWatch  implements java.io.Serializable {


     private int systemId;
     private String systemName;
     private Serializable systemvalue;

    public SystemWatch() {
    }

	
    public SystemWatch(int systemId) {
        this.systemId = systemId;
    }
    public SystemWatch(int systemId, String systemName, Serializable systemvalue) {
       this.systemId = systemId;
       this.systemName = systemName;
       this.systemvalue = systemvalue;
    }
   
    public int getSystemId() {
        return this.systemId;
    }
    
    public void setSystemId(int systemId) {
        this.systemId = systemId;
    }
    public String getSystemName() {
        return this.systemName;
    }
    
    public void setSystemName(String systemName) {
        this.systemName = systemName;
    }
    public Serializable getSystemvalue() {
        return this.systemvalue;
    }
    
    public void setSystemvalue(Serializable systemvalue) {
        this.systemvalue = systemvalue;
    }




}


